module.exports = [
  {
    warningDesc: '',
    orderNo: 1,
    warningIsDisplay: null,
    funcIcon: 'fa fa-slideshare',
    funcCode: '',
    funcDesc: '',
    parentId: null,
    isDisplay: 1,
    funcName: '用户洞察',
    funcUrl: '',
    children: [
      {
        warningDesc: null,
        orderNo: 1,
        warningIsDisplay: null,
        funcIcon: null,
        funcCode: null,
        funcDesc: null,
        parentId: '1000',
        isDisplay: 1,
        funcName: '单用户画像',
        funcUrl: null,
        children: [
          {
            warningDesc: null,
            orderNo: 1,
            warningIsDisplay: null,
            funcIcon: '',
            funcCode: '',
            funcDesc: null,
            parentId: '1100',
            isDisplay: 1,
            funcName: '意向客户查询',
            funcUrl: '/portrait/singleportrait/customer-behavior-query',
            children: null,
            appId: 'datacube_athena',
            id: 'da3148cba79e409cbc93f2654acd5c1a',
            funcType: 2,
          },
          {
            warningDesc: null,
            orderNo: 2,
            warningIsDisplay: null,
            funcIcon: 'fa fa-id-badge',
            funcCode: '',
            funcDesc: null,
            parentId: '1100',
            isDisplay: 1,
            funcName: '客户画像查询',
            funcUrl: '/portrait/singleportrait/customer-manager-search',
            children: null,
            appId: 'datacube_athena',
            id: '1120',
            funcType: 2,
          },
          {
            warningDesc: null,
            orderNo: 3,
            warningIsDisplay: null,
            funcIcon: 'fa fa-building-o',
            funcCode: '',
            funcDesc: null,
            parentId: '1100',
            isDisplay: 1,
            funcName: '高级查询',
            funcUrl: '/portrait/singleportrait/sales-department-search',
            children: null,
            appId: 'datacube_athena',
            id: '1130',
            funcType: 2,
          },
          {
            warningDesc: null,
            orderNo: 4,
            warningIsDisplay: null,
            funcIcon: 'fa fa-twitch',
            funcCode: '',
            funcDesc: null,
            parentId: '1100',
            isDisplay: 1,
            funcName: '通用查询',
            funcUrl: '/portrait/singleportrait/search-user',
            children: [
              {
                warningDesc: null,
                orderNo: 1,
                warningIsDisplay: null,
                funcIcon: '',
                funcCode: 'ACCOUNT_FROZEN_STATE',
                funcDesc: null,
                parentId: '1110',
                isDisplay: null,
                funcName: '冻结状态',
                funcUrl: '/portrait/business/query4UserGrantFrozenList',
                children: null,
                appId: 'datacube_athena',
                id: '510219ede8b44890972409437047e6f5',
                funcType: 3,
              },
              {
                warningDesc: null,
                orderNo: 2,
                warningIsDisplay: null,
                funcIcon: '',
                funcCode: 'ACCOUNT_CREDIT_STATE',
                funcDesc: null,
                parentId: '1110',
                isDisplay: null,
                funcName: '授信状态',
                funcUrl: '/portrait/business/query4UserCreditOperationRecord',
                children: null,
                appId: 'datacube_athena',
                id: '96219f229b214289a95da269b5b018cb',
                funcType: 3,
              },
            ],
            appId: 'datacube_athena',
            id: '1110',
            funcType: 2,
          },
          {
            warningDesc: null,
            orderNo: null,
            warningIsDisplay: null,
            funcIcon: 'fa fa-id-badge',
            funcCode: '',
            funcDesc: null,
            parentId: '1100',
            isDisplay: 1,
            funcName: '客户经理监察',
            funcUrl: '/portrait/singleportrait/customer-manager-inspect',
            children: [
              {
                warningDesc: null,
                orderNo: 1,
                warningIsDisplay: null,
                funcIcon: '',
                funcCode: 'INSPECT_PORTRAIT_EXOPRT',
                funcDesc: null,
                parentId: '1140',
                isDisplay: null,
                funcName: '用户画像导出按钮',
                funcUrl: '/portrait/user/exportAccountManaPortrait',
                children: null,
                appId: 'datacube_athena',
                id: 'd0b000bf348f43c08b34c1904c693b9d',
                funcType: 3,
              },
              {
                warningDesc: null,
                orderNo: 2,
                warningIsDisplay: null,
                funcIcon: '',
                funcCode: 'CUSTOMER_MANAGER_INSPECT_PHOTOALBUM',
                funcDesc: null,
                parentId: '1140',
                isDisplay: null,
                funcName: '用户照片记录按钮',
                funcUrl: '/portrait/user/query4UserPhotoValues',
                children: null,
                appId: 'datacube_athena',
                id: '89a025a358874c84a28b03b9af8d5305',
                funcType: 3,
              },
            ],
            appId: 'datacube_athena',
            id: '1140',
            funcType: 2,
          },
        ],
        appId: 'datacube_athena',
        id: '1100',
        funcType: 1,
      },
      {
        warningDesc: null,
        orderNo: 2,
        warningIsDisplay: null,
        funcIcon: 'fa fa-file-image-o',
        funcCode: '',
        funcDesc: null,
        parentId: '1000',
        isDisplay: 0,
        funcName: '用户群画像Beta',
        funcUrl: '/portrait/groupportrait/group-portrait-overview-demo',
        children: null,
        appId: 'datacube_athena',
        id: '1200',
        funcType: 2,
      },
      {
        warningDesc: null,
        orderNo: 3,
        warningIsDisplay: null,
        funcIcon: '',
        funcCode: '',
        funcDesc: null,
        parentId: '1000',
        isDisplay: 1,
        funcName: '用户群画像',
        funcUrl: '/portrait/groupportrait/group-portrait-overview',
        children: null,
        appId: 'datacube_athena',
        id: 'a618a29233544fe7bc0e2b1c6fd94942',
        funcType: 2,
      },
      {
        warningDesc: null,
        orderNo: 4,
        warningIsDisplay: null,
        funcIcon: '',
        funcCode: '',
        funcDesc: null,
        parentId: '1000',
        isDisplay: 1,
        funcName: '用户关联信息查询',
        funcUrl: '/portrait/relateportrait/related-info-query',
        children: null,
        appId: 'datacube_athena',
        id: '7734bdfdf878489c9149db1864fcd417',
        funcType: 2,
      },
      {
        warningDesc: null,
        orderNo: 5,
        warningIsDisplay: null,
        funcIcon: '',
        funcCode: '',
        funcDesc: null,
        parentId: '1000',
        isDisplay: 1,
        funcName: '意向/风险用户查询',
        funcUrl:
          '/portrait/intentionandriskportrait/intention-and-risk-portrait',
        children: null,
        appId: 'datacube_athena',
        id: '5cb0b0056ebd435a9a49a53fc7bfc49b',
        funcType: 1,
      },
      {
        warningDesc: null,
        orderNo: 6,
        warningIsDisplay: null,
        funcIcon: '',
        funcCode: '',
        funcDesc: null,
        parentId: '1000',
        isDisplay: 1,
        funcName: '不良用户导流统计',
        funcUrl: '/portrait/bad-user-diversion-statistics',
        children: [
          {
            warningDesc: null,
            orderNo: 1,
            warningIsDisplay: null,
            funcIcon: '',
            funcCode: 'USER_DIVERSION_STATISTICS_BADDETAIL_EXP',
            funcDesc: null,
            parentId: '2b1e693faa624cb49cf41f09dd8783c2',
            isDisplay: null,
            funcName: '不良用户明细-导出按钮',
            funcUrl: '',
            children: null,
            appId: 'datacube_athena',
            id: 'b556f7caa0814053b3cb3427cbd3cef9',
            funcType: 3,
          },
          {
            warningDesc: null,
            orderNo: 2,
            warningIsDisplay: null,
            funcIcon: '',
            funcCode: 'USER_DIVERSION_STATISTICS_DIVERSIONDETAIL_EXP',
            funcDesc: null,
            parentId: '2b1e693faa624cb49cf41f09dd8783c2',
            isDisplay: null,
            funcName: '导流结果明细-导出按钮',
            funcUrl: '',
            children: null,
            appId: 'datacube_athena',
            id: 'c0e2228bd5224a38a4bda601987232c0',
            funcType: 3,
          },
          {
            warningDesc: null,
            orderNo: 3,
            warningIsDisplay: null,
            funcIcon: '',
            funcCode: 'USER_DIVERSION_STATISTICS_DIVERSIONSTATISTICS_EXP',
            funcDesc: null,
            parentId: '2b1e693faa624cb49cf41f09dd8783c2',
            isDisplay: null,
            funcName: '导流统计-导出按钮',
            funcUrl: '',
            children: null,
            appId: 'datacube_athena',
            id: 'c44cabc518bc4612b4cded729ee2ca27',
            funcType: 3,
          },
          {
            warningDesc: null,
            orderNo: 4,
            warningIsDisplay: null,
            funcIcon: '',
            funcCode: 'USER_DIVERSION_STATISTICS_ACTIONDETAIL_EXP',
            funcDesc: null,
            parentId: '2b1e693faa624cb49cf41f09dd8783c2',
            isDisplay: null,
            funcName: '导流行为统计-导出按钮',
            funcUrl: '',
            children: null,
            appId: 'datacube_athena',
            id: 'edd9d9387ef64ad9b9f6b48f4f4d2339',
            funcType: 3,
          },
          {
            warningDesc: null,
            orderNo: 5,
            warningIsDisplay: null,
            funcIcon: '',
            funcCode: 'USER_DIVERSION_STATISTICS_BADDETAIL',
            funcDesc: null,
            parentId: '2b1e693faa624cb49cf41f09dd8783c2',
            isDisplay: null,
            funcName: '不良用户明细-权限按钮',
            funcUrl: '',
            children: null,
            appId: 'datacube_athena',
            id: 'a266dc92e4c24212ac9bd494efc1ad10',
            funcType: 3,
          },
          {
            warningDesc: null,
            orderNo: 6,
            warningIsDisplay: null,
            funcIcon: '',
            funcCode: 'USER_DIVERSION_STATISTICS_DIVERSIONDETAIL',
            funcDesc: null,
            parentId: '2b1e693faa624cb49cf41f09dd8783c2',
            isDisplay: null,
            funcName: '导流结果明细-权限按钮',
            funcUrl: '',
            children: null,
            appId: 'datacube_athena',
            id: '8cf803fb1fe1466392dd9c1b25fc27dc',
            funcType: 3,
          },
          {
            warningDesc: null,
            orderNo: 7,
            warningIsDisplay: null,
            funcIcon: '',
            funcCode: 'USER_DIVERSION_STATISTICS_DIVERSIONSTATISTICS',
            funcDesc: null,
            parentId: '2b1e693faa624cb49cf41f09dd8783c2',
            isDisplay: null,
            funcName: '导流统计-权限按钮',
            funcUrl: '',
            children: null,
            appId: 'datacube_athena',
            id: '6e6920f50c604b3f9d668979eb3175b4',
            funcType: 3,
          },
          {
            warningDesc: null,
            orderNo: 8,
            warningIsDisplay: null,
            funcIcon: '',
            funcCode: 'USER_DIVERSION_STATISTICS_ACTIONDETAIL',
            funcDesc: null,
            parentId: '2b1e693faa624cb49cf41f09dd8783c2',
            isDisplay: null,
            funcName: '导流行为统计-权限按钮',
            funcUrl: '',
            children: null,
            appId: 'datacube_athena',
            id: '34020b068090493e8e725ccf151d6722',
            funcType: 3,
          },
        ],
        appId: 'datacube_athena',
        id: '2b1e693faa624cb49cf41f09dd8783c2',
        funcType: 2,
      },
    ],
    appId: 'datacube_athena',
    id: '1000',
    funcType: 1,
  },
  {
    warningDesc: null,
    orderNo: 2,
    warningIsDisplay: null,
    funcIcon: 'fa fa-search',
    funcCode: '',
    funcDesc: null,
    parentId: null,
    isDisplay: 1,
    funcName: '自助查询分析',
    funcUrl: '',
    children: [
      {
        warningDesc: null,
        orderNo: 1,
        warningIsDisplay: null,
        funcIcon: 'fa fa-search',
        funcCode: null,
        funcDesc: null,
        parentId: '2000',
        isDisplay: 1,
        funcName: '用户自助查询',
        funcUrl: '/selfquery/user-self-query',
        children: [
          {
            warningDesc: null,
            orderNo: 1,
            warningIsDisplay: null,
            funcIcon: null,
            funcCode: 'user_self_query_export',
            funcDesc: null,
            parentId: '2100',
            isDisplay: 1,
            funcName: '数据导出按钮',
            funcUrl: '/selfquery/user/export/doExport',
            children: null,
            appId: 'datacube_athena',
            id: '2101',
            funcType: 3,
          },
        ],
        appId: 'datacube_athena',
        id: '2100',
        funcType: 2,
      },
      {
        warningDesc: null,
        orderNo: 2,
        warningIsDisplay: null,
        funcIcon: 'fa fa-shopping-basket',
        funcCode: null,
        funcDesc: null,
        parentId: '2000',
        isDisplay: 1,
        funcName: '产品自助查询',
        funcUrl: '/selfquery/product-self-query',
        children: null,
        appId: 'datacube_athena',
        id: '2200',
        funcType: 2,
      },
      {
        warningDesc: null,
        orderNo: 3,
        warningIsDisplay: null,
        funcIcon: 'fa fa-search',
        funcCode: null,
        funcDesc: null,
        parentId: '2000',
        isDisplay: 1,
        funcName: '业务自助查询',
        funcUrl: '/common/comming-soon?id=4',
        children: null,
        appId: 'datacube_athena',
        id: '2300',
        funcType: 2,
      },
      {
        warningDesc: null,
        orderNo: 5,
        warningIsDisplay: null,
        funcIcon: '',
        funcCode: '',
        funcDesc: null,
        parentId: '2000',
        isDisplay: 1,
        funcName: '指标自助查询',
        funcUrl: '/selfquery/indicator-self-query',
        children: [
          {
            warningDesc: null,
            orderNo: 1,
            warningIsDisplay: null,
            funcIcon: '',
            funcCode: 'INDICATOR_SELF_QUERY_EXPORT',
            funcDesc: null,
            parentId: '1594b440118f4b20af4b4775cccf62ad',
            isDisplay: null,
            funcName: '指标自助查询导出与查看下载按钮',
            funcUrl: '',
            children: null,
            appId: 'datacube_athena',
            id: '954a22c30dd243e3bb5ca3026cd0b489',
            funcType: 3,
          },
          {
            warningDesc: null,
            orderNo: 2,
            warningIsDisplay: null,
            funcIcon: '',
            funcCode: 'INDICATOR_SELF_QUERY_CUBE_INST_SEL',
            funcDesc: null,
            parentId: '1594b440118f4b20af4b4775cccf62ad',
            isDisplay: null,
            funcName: '指标自助查询模型实例选择',
            funcUrl: '',
            children: null,
            appId: 'datacube_athena',
            id: 'f56be93a250241659440e4c4226207a1',
            funcType: 5,
          },
        ],
        appId: 'datacube_athena',
        id: '1594b440118f4b20af4b4775cccf62ad',
        funcType: 2,
      },
      {
        warningDesc: null,
        orderNo: 6,
        warningIsDisplay: null,
        funcIcon: 'fa fa-download',
        funcCode: null,
        funcDesc: null,
        parentId: '2000',
        isDisplay: 1,
        funcName: '数据下载',
        funcUrl: '/selfquery/data-download',
        children: null,
        appId: 'datacube_athena',
        id: '2500',
        funcType: 2,
      },
      {
        warningDesc: null,
        orderNo: 7,
        warningIsDisplay: null,
        funcIcon: '',
        funcCode: '',
        funcDesc: null,
        parentId: '2000',
        isDisplay: 1,
        funcName: '数据推送',
        funcUrl: '/selfquery/data-push',
        children: [
          {
            warningDesc: null,
            orderNo: 1,
            warningIsDisplay: null,
            funcIcon: '',
            funcCode: 'APP_MSG_TOOL',
            funcDesc: null,
            parentId: '7f0640d402b84c9d9965686acea955d3',
            isDisplay: null,
            funcName: '短信工具',
            funcUrl: '',
            children: null,
            appId: 'datacube_athena',
            id: '174c24a92427458ca47263602616355a',
            funcType: 3,
          },
          {
            warningDesc: null,
            orderNo: 2,
            warningIsDisplay: null,
            funcIcon: '',
            funcCode: 'APP_ADDRESS_TOOL',
            funcDesc: null,
            parentId: '7f0640d402b84c9d9965686acea955d3',
            isDisplay: null,
            funcName: '通讯录获取工具',
            funcUrl: '',
            children: null,
            appId: 'datacube_athena',
            id: '7e0759a8d7c74f9fb7dcf890a47f0f83',
            funcType: 3,
          },
          {
            warningDesc: null,
            orderNo: 3,
            warningIsDisplay: null,
            funcIcon: '',
            funcCode: 'APP_BOSS_TOOL',
            funcDesc: null,
            parentId: '7f0640d402b84c9d9965686acea955d3',
            isDisplay: null,
            funcName: 'boss用户分群',
            funcUrl: '',
            children: null,
            appId: 'datacube_athena',
            id: '65a26934e5c84d34952f41616d78be08',
            funcType: 3,
          },
        ],
        appId: 'datacube_athena',
        id: '7f0640d402b84c9d9965686acea955d3',
        funcType: 2,
      },
    ],
    appId: 'datacube_athena',
    id: '2000',
    funcType: 1,
  },
];
